version: '3'

networks:
    guki:

services:
    apache:
        image: bitnami/apache:latest
        container_name: guki_apache
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./code:/var/www/html/
            - ./configs/vhosts/:/etc/apache2/sites-enabled/
            - ./logs/apache2/:/var/log/apache2
            # certificates
            - ./configs/certs/:/etc/apache2/certs/:ro
        depends_on:
            - php7_3
            # you may add more version here like the one below
            # - php7_2
        networks:
            - guki

    mysql:
        image: mysql:5.7
        container_name: guki_mysql
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
            - ${MYSQL_LOG_DIR}:/var/log/mysql:rw
        ports:
            - "3306:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=Rkme#001
            - MYSQL_DATABASE=rkme
            - MYSQL_USER=rkme
            - MYSQL_PASSWORD=Rkme#001
        networks:
            - guki

    php7_3:
        build: 
            context: './builds/php7_3/'
        container_name: guki_php7_3
        volumes:
            - ./code:/var/www/html
            - ./configs/php.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
        networks:
            - guki

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: guki_phpmyadmin
        ports:
            - "8080:80"
        environment:        
            PMA_ARBITRARY: 1
        depends_on:
            - mysql
        networks:
            - guki
            
    redis:
        image: redis:latest
        container_name: guki_redis
        ports:
            - "6379:6379"
        networks:
            - guki