version: '3'

networks:
    guki:

services:
    nginx:
        image: nginx:stable
        container_name: guki_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./code:/var/www/html/
            - ./configs/vhosts/:/etc/nginx/conf.d/
            # certificates
            - ./configs/certs/:/etc/nginx/certs/:ro
        depends_on:
            - php7_2
            # - php7_1
            - php5_6
        networks:
            - guki

    mysql:
        image: mysql:5.7
        container_name: guki_mysql
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
            - ${MYSQL_LOG_DIR}:/var/log/mysql:rw
        ports:
            - "3307:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=Rkme#001
            - MYSQL_DATABASE=rkme
            - MYSQL_USER=rkme
            - MYSQL_PASSWORD=Rkme#001         
        networks:
            - guki

    php7_2:
        build: 
            context: './builds/php7_2/'
        container_name: guki_php7_2
        volumes:
            - ./code:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - guki

    # php7_1:
    #     build: 
    #         context: './builds/php7_1/'
    #     container_name: guki_php7_1
    #     volumes:
    #         - ./code:/var/www/html
    #     ports:
    #         - "9001:9001"
    #     networks:
    #         - guki

    php5_6:
        build: 
            context: './builds/php5_6/'
        container_name: guki_php5_6
        volumes:
            - ./code:/var/www/html
        ports:
            - "9002:9002"
        networks:
            - guki

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: guki_phpmyadmin
        ports:
            - "8080:80"
        environment:        
            PMA_ARBITRARY: 1
        depends_on:
            - mysql
        networks:
            - guki
    redis:
        image: redis:latest
        container_name: guki_redis
        ports:
            - "6379:6379"



